FROM golang:1.21-alpine
RUN apk add alpine-sdk 
RUN apk --update add git
WORKDIR /app
COPY go.* ./
RUN go mod download
# Copy the source from the current directory to the Working Directory inside the container
COPY . .
RUN go mod download
RUN GOOS=linux GOARCH=amd64 go build -tags musl -o main ./cmd/nuevotwitt/main.go
#RUN go build -v -o main ./cmd/nuevotwitt/main.go
# Expose port 8080 to the outside world
#EXPOSE 8080
# Run the executable
CMD ["/app/main"]
