version: '2'

services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      #- REDIS_PASSWORD=my_master_password
      - ALLOW_EMPTY_PASSWORD=yes
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      #primero crear el dir ./redis-persistence con permisos 777
      - ./redis-persistence:/bitnami
      - ./redis.conf:/opt/bitnami/redis/etc/redis.conf
